version: '3.1'

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_user_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /praca_inzynierska/server/db:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db

  mosquitto:
    image: iegomez/mosquitto-go-auth
    container_name: mosquitto
    volumes:
      - /praca_inzynierska/server/mosquitto/config:/etc/mosquitto/
      - /praca_inzynierska/server/mosquitto/conf.d:/etc/mosquitto/conf.d
      - /praca_inzynierska/server/mosquitto/data:/mosquitto/data
      - /praca_inzynierska/server/mosquitto/log:/mosquitto/log
      # - /praca_inzynierska/server/mosquitto/shared:/mosquitto/shared
    ports:
      - 1883:1883
      - 9001:9001   



