version: '3.1'

services:
  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /home/student/praca_inzynierska/server/opt/mosquitto:/mosquitto
      - /home/student/praca_inzynierska/server/opt/mosquitto/data:/mosquitto/data
      - /home/student/praca_inzynierska/server/opt/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001   

  mosquitto-go-auth:
    image: iegomez/mosquitto-go-auth
    container_name: mosquitto-go-auth
    volumes:
      - 

